const queenData = {
    monet: {
        name: "Monet X Change",
        profilePic: "images/monet.jpeg",
        season: "S10 / AS4 / AS7",
        avatar: "images/monet-avatar.jpg",
    },
    katya: {
        name: "Katya Zamolodchikova",
        profilePic: "images/katya.jpeg",
        season: "S7 / AS2",
        avatar: "images/katya-avatar.jpg",
    },
    raja: {
        name: "Raja Gemini",
        profilePic: "images/raja.jpeg",
        season: "S3 / AS7",
        avatar: "images/raja-avatar.jpg",
    },
    bob: {
        name: "Bob the Drag Queen",
        profilePic: "images/bob.jpeg",
        season: "S8",
        avatar: "images/bob-avatar.jpg",
    },
    trixie: {
        name: "Trixie Mattel",
        profilePic: "images/trixie.jpeg",
        season: "S7 / AS3",
        avatar: "images/trixie-avatar.jpg",
    },
    jinkx: {
        name: "Jinkx Monsoon",
        profilePic: "images/jinkx.jpeg",
        season: "S5 / AS7",
        avatar: "images/jinkx-avatar.jpg",
    },
    adore: {
        name: "Adore Delano",
        profilePic: "images/adore.jpeg",
        season: "S6 / AS2",
        avatar: "images/adore-avatar.jpg",
    },
    kandy: {
        name: "Kandy Muse",
        profilePic: "images/kandy.jpeg",
        season: "S13 / AS8",
        avatar: "images/kandy-avatar.jpg",
    },
    jaida: {
        name: "Jaida Essence Hall",
        profilePic: "images/jaida.jpeg",
        season: "S12 / AS7",
        avatar: "images/jaida-avatar.jpg",
    },
    rajah: {
        name: "Ra'Jah O'Hara",
        profilePic: "images/rajah.jpeg",
        season: "S11 / AS6",
        avatar: "images/rajah-avatar.jpg",
    },
    shea: {
        name: "Shea Couleé",
        profilePic: "images/shea.jpeg",
        season: "S9 / AS5",
        avatar: "images/shea-avatar.jpg",
    },
    alaska: {
        name: "Alaska",
        profilePic: "images/alaska.jpeg",
        season: "S5 / AS2",
        avatar: "images/alaska-avatar.jpg",
    },
    crystal: {
        name: "Crystal Methyd",
        profilePic: "images/crystal.jpeg",
        season: "S12",
        avatar: "images/crystal-avatar.jpg",
    },
    cracker: {
        name: "Miz Cracker",
        profilePic: "images/cracker.jpeg",
        season: "S10 / AS5",
        avatar: "images/cracker-avatar.jpg",
    },
    kylie: {
        name: "Kylie Sonique Love",
        profilePic: "images/kylie.jpeg",
        season: "S2 / AS6",
        avatar: "images/kylie-avatar.jpg",
    },
    jan: {
        name: "Jan Sport",
        profilePic: "images/jan.jpeg",
        season: "S12 / AS6",
        avatar: "images/jan-avatar.jpg",
    },
    jujubee: {
        name: "Jujubee",
        profilePic: "images/jujubee.jpeg",
        season: "S2 / AS1 / AS5",
        avatar: "images/jujubee-avatar.jpg",
    },
    kim: {
        name: "Kim Chi",
        profilePic: "images/kim.jpeg",
        season: "S8",
        avatar: "images/kim-avatar.jpg",
    },
    tammie: {
        name: "Tammie Brown",
        profilePic: "images/tammie.jpeg",
        season: "S1 / AS1",
        avatar: "images/tammie-avatar.jpg",
    },
    chichi: {
        name: "Chi Chi DeVayne",
        profilePic: "images/chichi.jpeg",
        season: "S8 / AS3",
        avatar: "images/chichi-avatar.jpg",
    },
    rupaul: {
        name: "RuPaul",
        profilePic: "images/rupaul.jpeg",
        season: "",
        avatar: "images/rupaul-avatar.jpg",
    },
    tatianna: {
        name: "Tatianna",
        profilePic: "images/tatianna.jpeg",
        season: "S2 / AS2",
        avatar: "images/tatianna-avatar.jpg",
    },
    alyssa: {
        name: "Alyssa Edwards",
        profilePic: "images/alyssa.jpeg",
        season: "S5 / AS2",
        avatar: "images/alyssa-avatar.jpg",
    },
    peppermint: {
        name: "Peppermint",
        profilePic: "images/peppermint.jpeg",
        season: "S9",
        avatar: "images/peppermint-avatar.jpg",
    },
}

export { queenData }
